hil: fix compile warning
hil uses sprintf so we need to include stdio.h for it, otherwise we get:

lib/common/hil.c: In function ‘hil_create_generic_mem_dev’:
lib/common/hil.c:112:2: warning: implicit declaration of function ‘sprintf’ [-Wimplicit-function-declaration]
  sprintf(dev->name, "%s%lx.%lx", HIL_DEV_NAME_PREFIX, pa,

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>